before_install:
  - gem update --system
  - gem install bundler
deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
  local-dir: _site
  target-branch: master
  skip-cleanup: true
  keep-history: true
  on:
    branch: draft
